### ISSUE TITLE
GITHUB_TOKEN documentation doesn't list what permissions it needs

### ISSUE THREAD

**Issue by Daenyth** [alejandrohdezma/sbt-github#347]
I'd like to use a token with the minimal set of permissions needed, but the documentation doesn't list what permissions are required.

Is there a list somewhere?

**Comment by alejandrohdezma** [comment]
Hey @Daenyth, I totally missed this opened issue. I have added it to documentation in #355.

**Comment by alejandrohdezma** [comment]
Oh! And thank you very much!

![](https://media.giphy.com/media/3o6Zt6KHxJTbXCnSvu/giphy.gif)
